const topic = {
  id: "fundamental-subspaces",
  title: "Fundamental Subspaces",
  summary:
    "Column, row, null and left-null spaces; bases for each and relationships between them.",
  details: `
Fundamental Subspaces are four important vector spaces associated with a matrix. They provide a deeper understanding of what a matrix does, what information it contains, and how it transforms vectors. These four subspaces are the Column Space, Row Space, Null Space, and Left Null Space.

Fundamental Subspaces are important because they help us understand linear systems, matrix transformations, linear independence, rank, nullity, and solutions to equations. They also show how the rows and columns of a matrix are related to the solutions of a system.

Suppose we have a matrix A ∈ ℝ^(m×n). The four fundamental subspaces associated with A are:

  • Column Space (Col A)
  • Row Space (Row A)
  • Null Space (Null A)
  • Left Null Space (Null Aᵀ)

The first two are subspaces of the appropriate input/output spaces, while the null spaces describe vectors that are mapped to zero.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. COLUMN SPACE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Column Space of a matrix is the set of all possible linear combinations of its columns. It is usually written as Col(A).

Example:

  A = [1  2]
      [2  4]
      [3  6]

The columns are:

  a₁ = [1]    a₂ = [2]
       [2]         [4]
       [3]         [6]

Notice that a₂ = 2a₁. Therefore, the second column does not provide a new independent direction.

The column space consists of all vectors that can be created using combinations of the columns:

  c₁[1] + c₂[2]
    [2]     [4]
    [3]     [6]

Because the second column is just a multiple of the first, the column space is essentially generated by:

  [1]
  [2]
  [3]

Therefore:

  Col(A) = span{ [1] }
                  [2]
                  [3]

────────────────────────────────────────────────────────────────────────────────

Why Is Column Space Important?

The column space tells us which vectors can be produced by multiplying A by some vector x.

If A x = b, then a solution exists only if b ∈ Col(A).

Therefore, the column space helps answer an important question: Can the system A x = b be solved?

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. ROW SPACE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Row Space is the set of all linear combinations of the rows of a matrix. It is written as Row(A).

Using the same matrix:

  A = [1  2]
      [2  4]
      [3  6]

The rows are:

  [1  2],  [2  4],  [3  6]

Again, the rows are all multiples of the first row:

  [2  4] = 2[1  2]
  [3  6] = 3[1  2]

Therefore:

  Row(A) = span{ [1  2] }

────────────────────────────────────────────────────────────────────────────────

Row Reduction and Row Space

One of the easiest ways to find a basis for the row space is to use row reduction.

Example:

  A = [1  2]
      [2  4]

can be reduced using R₂ → R₂ - 2R₁. This produces:

  [1  2]
  [0  0]

The nonzero row [1  2] forms a basis for the row space.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

3. NULL SPACE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Null Space is one of the most important fundamental subspaces.

The null space of A is the set of all vectors x that satisfy:

  A x = 0

It is written as Null(A).

In simple terms, the null space contains all input vectors that the matrix transforms into the zero vector.

Example:

  A = [1  2]
      [2  4]

We want to solve A x = 0.

Let x = [x]. Then:
        [y]

  [1  2] [x] = [0]
  [2  4] [y]   [0]

This produces the equation:

  x + 2y = 0

Therefore:

  x = -2y

Let y = t. Then x = -2t.

Therefore:

  x = t[-2]
        [ 1]

So:

  Null(A) = span{ [-2] }
                   [ 1]

This means that every multiple of [-2, 1]ᵀ is mapped to zero by A.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. LEFT NULL SPACE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The fourth fundamental subspace is the Left Null Space.

The left null space consists of all vectors y satisfying:

  Aᵀ y = 0

It is therefore the null space of the transpose: Null(Aᵀ).

Example:

  A = [1  2]
      [2  4]
      [3  6]

Then:

  Aᵀ = [1  2  3]
       [2  4  6]

To find the left null space, solve Aᵀ y = 0.

Let y = [y₁]
         [y₂]
         [y₃]

Then:

  [1  2  3] [y₁] = [0]
  [2  4  6] [y₂]   [0]
             [y₃]

This produces:

  y₁ + 2y₂ + 3y₃ = 0

There are two free variables, so the left null space has dimension 2.

The left null space is useful for understanding relationships among the rows and the constraints represented by a matrix.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

5. THE FOUR FUNDAMENTAL SUBSPACES SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The four spaces can be summarized as follows:

Subspace              Definition                                    Main Question
---------             -----------                                   -------------
Column Space (Col A)  Span of the columns of A                      What outputs can A produce?
Row Space (Row A)     Span of the rows of A                         What independent equations does A contain?
Null Space (Null A)   Solutions of A x = 0                         Which inputs become zero?
Left Null Space       Solutions of Aᵀ y = 0                        Which vectors are orthogonal to the column space?
(Null Aᵀ)

These four spaces are deeply connected.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

6. RANK AND NULLITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Fundamental Subspaces are closely related to rank and nullity.

The rank of a matrix is the dimension of its column space:

  rank(A) = dim(Col(A))

The rank is also equal to the dimension of the row space:

  rank(A) = dim(Row(A))

The nullity is the dimension of the null space:

  nullity(A) = dim(Null(A))

These quantities are connected through the Rank-Nullity Theorem:

  rank(A) + nullity(A) = n

where n is the number of columns of A.

Example:

  A = [1  2]
      [2  4]

The rank is 1, because there is only one independent column.

The nullity is also 1, because there is one free variable.

Therefore:

  1 + 1 = 2

Since A has 2 columns, the Rank-Nullity Theorem is satisfied.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

7. FUNDAMENTAL SUBSPACES AND ORTHOGONALITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

An important property of the four fundamental subspaces is that they are related through orthogonality.

  Null(A) ⟂ Row(A)

  Null(Aᵀ) ⟂ Col(A)

This means that vectors in one of these spaces have a dot product of zero with vectors in the corresponding other space.

Example:

  A = [1  2]
      [2  4]

A vector in its row space is:

  [1]
  [2]

A vector in its null space is:

  [-2]
  [ 1]

Their dot product is:

  (1)(-2) + (2)(1) = -2 + 2 = 0

Therefore, the vectors are orthogonal.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

8. GEOMETRIC INTERPRETATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Fundamental Subspaces can also be understood geometrically.

  • The column space represents the possible outputs of a matrix transformation.

  • The null space represents the directions that disappear when the transformation is applied.

  • The row space represents the independent information contained in the equations.

  • The left null space represents vectors that are orthogonal to every vector in the column space.

Think of a matrix as a machine:

  x  →  A  →  A x

  • The null space tells us which inputs produce A x = 0.

  • The column space tells us which outputs are possible.

This provides a useful way to understand what a matrix transformation is actually doing.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

9. EXAMPLE USING A COMPLETE MATRIX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Consider:

  A = [1  2]
      [2  4]

Column Space:

  The columns are [1] and [2].
                  [2]     [4]

  Since the second column is twice the first:

  Col(A) = span{ [1] }
                 [2]

Row Space:

  The rows are [1  2] and [2  4].

  Row(A) = span{ [1  2] }

Null Space:

  Solve A x = 0. We obtain x + 2y = 0, so x = -2y.

  Null(A) = span{ [-2] }
                   [ 1]

Left Null Space:

  Since Aᵀ = A, we solve Aᵀ y = 0.

  Null(Aᵀ) = span{ [-2] }
                    [ 1]

Thus, this matrix demonstrates all four fundamental subspaces.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

10. APPLICATIONS OF FUNDAMENTAL SUBSPACES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Fundamental Subspaces have many applications in mathematics, science, engineering, and computer science.

  1. Solving Systems of Equations
     • The column space determines whether a system has a solution
     • The null space helps describe all possible solutions

  2. Data Science
     • Identifying important directions in datasets
     • Determining relationships among variables

  3. Machine Learning
     • Optimization problems
     • Solving systems involving large datasets

  4. Computer Graphics
     • Representing objects and transformations
     • Analyzing geometric relationships

  5. Engineering
     • Analyzing systems of equations
     • Constraints, signals, and physical models

  6. Least-Squares Problems
     • Finding the best approximate solution
     • When a system may not have an exact solution

  7. Signal Processing
     • Analyzing signals and noise
     • Filtering and reconstruction

  8. Statistics
     • Regression analysis
     • Variance and covariance analysis

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In summary, the Fundamental Subspaces are four important vector spaces associated with a matrix:

  • Col(A)  →  Column Space
  • Row(A)  →  Row Space
  • Null(A) →  Null Space
  • Null(Aᵀ) → Left Null Space

Summary of Each Subspace:

  • Column Space: What outputs a matrix can produce.
  • Row Space: The independent information contained in the rows.
  • Null Space: The vectors that are transformed into zero.
  • Left Null Space: The null space of the transpose, orthogonal to the column space.

These spaces are connected through:

  rank(A) = dim(Col(A)) = dim(Row(A))

  nullity(A) = dim(Null(A))

  rank(A) + nullity(A) = n  (Rank-Nullity Theorem)

And through orthogonality:

  Null(A) ⟂ Row(A)

  Null(Aᵀ) ⟂ Col(A)

The key idea to remember:

  The four fundamental subspaces reveal the complete structure of a matrix—what it can produce, what information it contains, what inputs disappear, and what relationships exist among its rows and columns.
  `,
  examples: [
    "Column Space: Find Col(A) for A = [[1,2],[2,4],[3,6]] → span{[1,2,3]ᵀ}",
    "Row Space: Find Row(A) for A = [[1,2],[2,4],[3,6]] → span{[1,2]}",
    "Null Space: Solve A x = 0 for A = [[1,2],[2,4]] → span{[-2,1]ᵀ}",
    "Left Null Space: Solve Aᵀ y = 0 for A = [[1,2],[2,4],[3,6]]",
    "Rank-Nullity Theorem: rank(A) + nullity(A) = n",
    "Orthogonality: Null(A) ⟂ Row(A)",
    "Find a basis for the column space.",
    "Compute the nullspace of a matrix",
    "Determine if a vector is in the column space",
    "Find the rank and nullity of a matrix",
  ],
};

export default topic;